env:
  global:
    - NDK_VERSION=r10e
sudo: false
language:
  - android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository

install:
  - wget http://dl.google.com/android/ndk/android-ndk-$NDK_VERSION-linux-x86_64.bin
  - chmod +x android-ndk-$NDK_VERSION-linux-x86_64.bin
  - ./android-ndk-$NDK_VERSION-linux-x86_64.bin | egrep -v ^Extracting
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-$NDK_VERSION
  - export PATH=${PATH}:${ANDROID_NDK_HOME}
script:
- ndk-build
- make -C external
- ./setup-ant
- ant release
before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - openssl aes-256-cbc -K $encrypted_96416221afd7_key -iv $encrypted_96416221afd7_iv -in my-release-key.keystore.enc -out my-release-key.keystore -d
  - cp bin/Orbot-*-unsigned.apk bin/Orbot-signed.apk
  - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore my-release-key.keystore -storepass $KEYSTORE_PASS bin/Orbot-signed.apk alias_name
  - $ANDROID_HOME/build-tools/23.0.3/zipalign -v 4 bin/Orbot-signed.apk bin/Orbot-signed-aligned.apk || $ANDROID_HOME/build-tools/21.1.2/zipalign -v 4 bin/Orbot-signed.apk bin/Orbot-signed-aligned.apk
  - echo -e "machine github.com\nlogin galeksandrp\npassword $GITHUB_TOKEN" >> ~/.netrc
  - git tag deploy-$(git describe --always) $TRAVIS_COMMIT || true
  - git push origin deploy-$(git describe --always)
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: 
  - bin/*.apk
  file_glob: true
  overwrite: true
  on:
    all_branches: true
branches:
  except:
    - /^deploy-.*$/
notifications:
  email: false
