env:
  global:
    - NDK_VERSION=r13b
sudo: false
language:
  - android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

install:
  - wget https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip
  - unzip -q android-ndk-r13b-linux-x86_64.zip
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-$NDK_VERSION
  - export PATH=${PATH}:${ANDROID_NDK_HOME}
  - openssl aes-256-cbc -K $encrypted_96416221afd7_key -iv $encrypted_96416221afd7_iv -in my-release-key.keystore.enc -out my-release-key.keystore -d
  - echo "RELEASE_STORE_FILE=../my-release-key.keystore" > gradle.properties
  - echo "RELEASE_STORE_PASSWORD=$KEYSTORE_PASS" >> gradle.properties
  - echo "RELEASE_KEY_ALIAS=alias_name" >> gradle.properties
  - echo "RELEASE_KEY_PASSWORD=$KEYSTORE_PASS" >> gradle.properties
before_script:
- make -C external
before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - echo -e "machine github.com\nlogin galeksandrp\npassword $GITHUB_TOKEN" >> ~/.netrc
  - git tag deploy-$(git describe --always) $TRAVIS_COMMIT || true
  - git push origin deploy-$(git describe --always)
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: 
  - bin/*.apk
  file_glob: true
  overwrite: true
  on:
    all_branches: true
branches:
  except:
    - /^deploy-.*$/
notifications:
  email: false
